dataset_name: movielens
domain: media_and_entertainment
version: 1m
source_url: https://grouplens.org/datasets/movielens/1m/
citation: |
  @article{movielens1m,
    author = {Harper, F. Maxwell and Konstan, Joseph A.},
    title = {The MovieLens Datasets: History and Context},
    year = {2015},
    volume = {5},
    number = {4},
    url = {https://doi.org/10.1145/2827872},
    doi = {10.1145/2827872},
    journal = {ACM Transactions on Interactive Intelligent Systems},
    articleno = {19}
  }

stakeholder_roles:
  consumer:
    supported: true
    id: [userid]
    features: [gender, age, occupation, zip-code]
  provider:
    supported: false
  upstream:
    supported: false
  downstream:
    supported: false
  system:
    supported: false
  third_party:
    supported: false

files:
  interactions: ratings.csv
  items: movies.csv
  users: users.csv

schema:
  user_identifier: [userid]
  item_identifier: [movieid]
  timestamp: [timestamp]
  rating: [rating]

item_features:
  object: [movieid, genres]
  float: []
  text: [title]
  misc: []
  exclude: []

interaction_features:
  object: [userid, movieid, timestamp]
  float: [rating]
  text: []
  misc: []
  exclude: []

user_features:
  object: [userid, gender, occupation, zip-code]
  float: [age]
  text: []
  misc: []
  exclude: []

other_features: null

taxonomy:
  interactions:
    user_id: [userid]
    item_id: [movieid]
    explicit_feedback: [rating]
    implicit_feedback: []
    timestamp: [timestamp]
    session_data: []
    interaction_context: []
    other: []
  items:
    item_id: [movieid]
    descriptive_features: [genres]
    content_features: [title]
    provider_upstream_info: []
    other: []
  users:
    user_id: [userid]
    demographics: [gender, age, occupation, zip-code]
    downstream_stakeholder_info: []
    additional_attributes: []
    other: []
  other: null
