dataset_name: steam
domain: media_and_entertainment
version: '2018'
source_url: https://github.com/kang205/SASRec
citation: "@misc{steam,\n     title={Self-Attentive Sequential Recommendation}, \n    author={Wang-Cheng Kang and Julian McAuley},\n\
  \    year={2018},      \n    eprint={1808.09781},      \n    archivePrefix={arXiv},      \n    url={https://arxiv.org/abs/1808.09781},\n\
  \    }\n"

stakeholder_roles:
  consumer:
    supported: true
    id: [user_id]
    features: []
  provider:
    supported: true
    id: []
    features: [publisher]
  upstream:
    supported: true
    id: []
    features: [developer]
  downstream:
    supported: false
  system:
    supported: false
  third_party:
    supported: false

files:
  interactions: steam_reviews.json
  items: steam_games.json
  users: null

schema:
  user_identifier: [user_id]
  item_identifier: [id, product_id]
  timestamp: []
  rating: []

item_features:
  object: [publisher, release_date, early_access, id, sentiment, genres, tags, specs]
  float: [discount_price, price]
  text: [app_name, title, url, reviews_url, developer]
  misc: []
  exclude: [metascore]

interaction_features:
  object: [product_id, page_order, date, early_access, page, found_funny, compensation, user_id]
  float: [hours, products]
  text: [username, text]
  misc: []
  exclude: []

user_features: null

other_features: null

taxonomy:
  interactions:
    user_id: [user_id]
    item_id: [product_id]
    explicit_feedback: [username, text]
    implicit_feedback: []
    timestamp: []
    session_data: []
    interaction_context: [hours, products, page_order, date, early_access, page, found_funny, compensation]
    other: []
  items:
    item_id: [id]
    descriptive_features: [genres, release_date, tags, discount_price, specs, price, early_access, sentiment]
    content_features: [app_name, title]
    provider_upstream_info: [publisher, developer]
    other: [url, reviews_url, metascore]
  users: null
  other: null
