dataset_name: xwines
domain: ecommerce_and_retail
source_url: https://github.com/rogerioxavier/X-Wines
citation: |
  @Article{xwines,
    AUTHOR = {de Azambuja, Rogério Xavier and Morais, A. Jorge and Filipe, Vítor},
    TITLE = {X-Wines: A Wine Dataset for Recommender Systems and Machine Learning},
    JOURNAL = {Big Data and Cognitive Computing},
    VOLUME = {7},
    YEAR = {2023},
    NUMBER = {1},
    ARTICLE-NUMBER = {20},
    URL = {https://www.mdpi.com/2504-2289/7/1/20},
    DOI = {10.3390/bdcc7010020}
    }

stakeholder_roles:
  consumer:
    supported: true
    id: [userid]
    features: []
  provider:
    supported: true
    id: [wineryid]
    features: [wineryname]
  upstream:
    supported: false
  downstream:
    supported: false
  system:
    supported: true
    features: [regionid, regionname, country, code]
  third_party:
    supported: false

files:
  interactions:
    filename: XWines_Full_21M_ratings.csv
    archive: XWines_Full_21M_ratings.zip
  items:
    filename: XWines_Full_100K_wines.csv
    archive: XWines_Full_100K_wines.zip
  users: null

schema:
  user_identifier: [userid]
  item_identifier: [wineid]
  timestamp: [date]
  rating: [rating]

item_features:
  token: [wineid, type, elaborate, grapes, body, acidity, code, regionid, wineryid]
  float: [abv]
  token_seq: [harmonize, vintages]
  text: [winename, country, regionname, wineryname, website]
  misc: []
  drop: []

interaction_features:
  token: [userid, wineid, vintage, date]
  float: [rating]
  token_seq: []
  text: []
  misc: []
  drop: [ratingid]

user_features: null

other_features: null

taxonomy:
  interactions:
    user_id: [userid]
    item_id: [wineid]
    explicit_feedback: [rating]
    implicit_feedback: []
    timestamp: [date]
    session_data: []
    interaction_context: [vintage]
    other: [ratingid]
  items:
    item_id: [wineid]
    descriptive_features: [type, elaborate, grapes, harmonize, abv, body, acidity, code, regionid, vintages]
    content_features: [winename, country, regionname]
    provider_upstream_info: [wineryid, wineryname]
    other: [website]
  users: null
  other: null
